name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-and-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/cypress-io/github-action
      - name: Install Dependencies
        run: yarn install

      - name: Cypress Run
        run: yarn run test:cy

      - name: Perform LightHouse Audit Tests
        run: yarn lh:serve:test

      - name: Generate LightHouse Badges
        run: yarn lh:badges